apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: db-service
  name: db-service
  namespace: default
spec:
  containers:
    - env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-db/cookbook?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
      image: index.docker.io/cookbook_db-service
      imagePullPolicy: IfNotPresent
      name: db-service
      ports:
        - containerPort: 8080
      resources: {}
  restartPolicy: OnFailure
status: {}
