version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    volumes:
      - $HOME/Desktop/MySQL-Snippets/school.sql:/school.sql
  ms-recipe:
    build: ./Recipe
    ports:
      - "5000:5000"
  ms-comment:
    build: ./Comment
    ports:
      - "5001:5000"
  db-service:
    build: ./dbservice
    ports:
      - "5002:5000"