apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-db-claim0
  name: mysql-db-claim0
  namespace: default
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumes:
    - name: my-configmap
      configMap:
        name: mysql-db-configmap
status: {}
