apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ms-recipe
  name: ms-recipe
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ms-recipe
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: ms-recipe
    spec:
      containers:
        - image: index.docker.io/cookbook_ms-recipe
          imagePullPolicy: IfNotPresent
          name: ms-recipe
          ports:
            - containerPort: 5002
          resources: {}
      restartPolicy: Always
status: {}
